### ISSUE TITLE
How can I make a library's dependencies resolve in a local project's `import_map.json`?

### ISSUE THREAD

**Issue by disjukr** [lucacasonato/esbuild_deno_loader#10]
I'm not sure if it's right to question here.

The situation is that I imported `"react"` in the [deno.land/x/wrp](https://deno.land/x/wrp@v0.0.2/react/useWrpClientImpl.ts#L2), and I imported that library along with [`import_map.json`](https://github.com/pbkit/pbkit.dev/blob/wrp/import_map.json) in the [fresh](https://github.com/lucacasonato/fresh) project.

Then the following error occurred:
```
Server listening on http://localhost:8000
Download https://deno.land/x/wrp@v0.0.2/react/react
✘ [ERROR] [plugin deno] The module was missing and could not be loaded.

    deno:https://deno.land/x/wrp@v0.0.2/react/useWrpClientImpl.ts:2:36:
      2 │ import { useEffect, useState } from "react";
        ╵                                     ~~~~~~~
```

How to reproduce the error:
```sh
git clone git@github.com:pbkit/pbkit.dev.git
cd pbkit.dev
git checkout wrp
deno task dev
open http://localhost:8000/wrp-example-host
```

**Comment by lucacasonato** [comment]
Please run `deno info main.ts` on your project and paste the output here.

**Comment by lucacasonato** [comment]
Oh, that version of `fresh` did not support import maps yet. Please try the latest version of fresh, as it does support import maps (and uses them by default).

**Comment by hyp3rflow** [comment]
@lucacasonato Did https://github.com/lucacasonato/fresh/pull/209 fix this issue?

**Comment by disjukr** [comment]
It seems fixed now. Thank you!

**Comment by disjukr** [comment]
Sorry I misunderstood.. another error this time.

```sh
Warning deno task is unstable and may drastically change in the future
Task dev deno run --watch --no-check -A main.ts
Watcher Process started.
error: Relative import path "react" not prefixed with / or ./ or ../
    at https://deno.land/x/wrp@v0.0.3/react/useWrpServer.ts:9:35
Watcher Process failed. Restarting on file change...
```

**Comment by hyp3rflow** [comment]
@lucacasonato we've noticed that we just forgot to add an import map flag on our deno task :q 
@disjukr it seems fixed :)
