### ISSUE TITLE
Remove warning message

### ISSUE THREAD

**Issue by oscarotero** [lucacasonato/esbuild_deno_loader#11]
Hi.
I want to use this loader in the esbuild plugin for Lume. The plugin detects the `importMap` value of the `deno.json` file automatically here: https://github.com/lumeland/lume/blob/76072b52df9e463d1ce2ce49c73da7e54f1dfbf1/plugins/esbuild.ts#L21

On run esbuild, I get the following warning in the console:
```
Warning the configuration file "file:///Users/oscarotero/testing/deno.json" contains an entry for "importMap" that is being ignored.
```

I think this error is because the loader runs internally deno with `Deno.run` and this `deno.json` file is detected automatically by deno, but the import map file was passed with the `--import-map` option.

If the import file is not passed (because should be detected by the deno.json file) the build fails with errors like:

```
✘ [ERROR] [plugin deno] The module was missing and could not be loaded.

    deno:file:///Users/oscarotero/testing/main.jsx:1:18:
      1 │ import React from "react";
```

Deno v1.22 introduced the `--no-config` flag, so I think it should be passed here: https://github.com/lucacasonato/esbuild_deno_loader/blob/main/src/deno.ts#L45 to avoid unexpected errors.

**Comment by oscarotero** [comment]
Ok, it looks like `--no-config` flag is valid only for `deno run`.

**Comment by lucacasonato** [comment]
https://github.com/lucacasonato/esbuild_deno_loader/pull/14 changes the `deno info` command to be run in a temp dir, so discovering `deno.json` files should not be an issue anymore. Also see https://github.com/denoland/deno/issues/14703

**Comment by oscarotero** [comment]
Ok, great, much better solution. Thanks!
