### ISSUE TITLE
Quick question: Is there a way to ignore `.css` entry points?

### ISSUE THREAD

**Issue by stephband** [lucacasonato/esbuild_deno_loader#134]
I just got this lovely set of plugins building my project, thank you. I was using ESbuild to bundle both JS and CSS – not together, but as separate entry points:

```js
es.build({
    entryPoints: [
        './module.js', 
        './module.css'
    ],

    plugins: [...denoPlugins({
        configPath: workingdir + 'deno.json',
        lockPath:   workingdir + 'deno.lock'
    })]
    
    ...
}
```

Unfortunately `denoPlugins()` borks when fed CSS.

```cli
Expected a JavaScript or TypeScript module, but identified a Unknown module. ...
```

Is there a way to get it to ignore these entry points?

**Comment by hesxenon** [comment]
there "kinda" is:
```ts
    {
      name: "skip css",
      setup: (build) => {
        build.onResolve({ filter: /\.css$/, namespace: "file" }, (args) => {
          return {
            path: Path.resolve(args.resolveDir, args.path),
          };
        });
        build.onLoad({ filter: /\.css$/, namespace: "file" }, (args) => {
          const contents = Deno.readFileSync(args.path);
          return {
            contents: contents,
            loader: "css",
          };
        });
        build.onResolve({ filter: /.*/, namespace: "data" }, (args) => {
          return args.kind !== "url-token" ? undefined : { external: true };
        });
      },
    },
    ...denoPlugins({
```
so this basically handles css resolution and loading before one of the denoPlugins has a chance to handle that.

**Comment by stephband** [comment]
Of course, whack a handler in *before* `denoPlugins()`. I don't know why I didn't try that, I think I was influenced by this text in the README "In most cases, the denoResolverPlugin should be the first plugin in the plugin array".

Thank you, this solves my problem.

**Comment by hesxenon** [comment]
yeah, but the issue still exists, no?
