### ISSUE TITLE
Doesn't work with `npm:` specifiers

### ISSUE THREAD

**Issue by Kycermann** [lucacasonato/esbuild_deno_loader#29]
> ✘ [ERROR] [plugin deno] Failed to call 'deno info' on 'file:///.../.../index.js'

This could potentially be solved with an `unstable` flag. I will open a PR when my last one is merged. Please take a look.

**Comment by mitchwadair** [comment]
Is there any work being done on this at the moment?

**Comment by bartlomieju** [comment]
@codesculpture, @ITSDOUGES and I are looking into this problem

**Comment by Ciantic** [comment]
I made a plugin to rewrite `npm:...` to `esm.sh` before deno plugin like this:

```typescript
await esbuild.build({
    plugins: [
        // ESBuild plugin to rewrite import starting "npm:" to "esm.sh" for https plugin
        {
            name: "the-npm-plugin",
            setup(build: any) {
                build.onResolve({ filter: /^npm:/ }, (args: any) => {
                    return {
                        path: args.path.replace(/^npm:/, "//esm.sh/"),
                        namespace: "https",
                    };
                });
            },
        },
        denoPlugin() as any,
    ],
```

However it doesn't utilize the cache, it seems to be downloading all of the files I rewrite like that on each build.

But it works for the time being.
