### ISSUE TITLE
Option to filter out protocols

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [lucacasonato/esbuild_deno_loader#32]
I'd like the option of, after resolving import_map links, not bundling external dependencies (http). Would it make sense to add an option for this (AFAIK the `externals` options of esbuild doesn't cover this)?

I could create a PR if needed. The idea would be that you could have a new option where you specify protocols that are external. For example

```typescript
esbuild.build({
  // ...
  plugins: [denoPlugin({ importMapURL, externals: ['https:']})]
}):
```

**Comment by lucacasonato** [comment]
Why does the externals option not cover this? Can we re-use that option? I'd be happy to review & merge a PR.

**Comment by mfulton26** [comment]
I ran into this issue today. Here's a small demonstration:

**main.tsx**
```tsx
import React from "https://esm.sh/react@18.2.0?dev";

export default function App() {
  return <h1>Hello, world!</h1>;
}
```

**demo.ts**
```ts
import * as esbuild from "https://deno.land/x/esbuild@v0.17.11/mod.js";
import { denoPlugin } from "https://deno.land/x/esbuild_deno_loader@0.6.0/mod.ts";

const result = await esbuild.build({
  plugins: [
    // @ts-expect-error types don't agree for some unrelated reason
    denoPlugin(),
  ],
  entryPoints: ["main.tsx"],
  outfile: "./dist/main.esm.js",
  bundle: true,
  format: "esm",
  external: ["https://deno.land/*"],
});

console.log(result.outputFiles);

esbuild.stop();
```

**dist/main.esm.js** should result in being a small file with an `import` statement for React but instead it bundles React.
