### ISSUE TITLE
readme example doesn't work, also undefined `Deno` objects appear in output

### ISSUE THREAD

**Issue by uriva** [lucacasonato/esbuild_deno_loader#50]
the example in the readme is broken (`..` instead of `...` and `denoPlugins` isn't in the imported target)

I've got it to work with small tweaks

```
import * as esbuild from "https://deno.land/x/esbuild@v0.17.11/mod.js";

import { NodeModulesPolyfillPlugin } from "npm:@esbuild-plugins/node-modules-polyfill";
import { denoPlugin } from "https://deno.land/x/esbuild_deno_loader@0.6.0/mod.ts";

// Import the WASM build on platforms where running subprocesses is not
// permitted, such as Deno Deploy, or when running without `--allow-run`.
// import * as esbuild from "https://deno.land/x/esbuild@v0.17.11/wasm.js";

const result = await esbuild.build({
  plugins: [
    NodeModulesPolyfillPlugin({ polyfills: { crypto: true } }),
    denoPlugin(),
  ],
  entryPoints: ["../portal/client/src/index.ts"],
  outfile: "./out.js",
  bundle: true,
  format: "esm",
});
console.log(result);
esbuild.stop();
```

but now I'm getting a result which has many `Deno` object references, and these are undefined in a browser environment.

Am I missing something obvious?

**Comment by lucacasonato** [comment]
I will need to see the contents of `../portal/client/src/index.ts` to be able to see what may be going wrong here.

**Comment by uriva** [comment]
maybe a preliminary question, is it a goal of this library to turn deno code that uses deno standard library into something that can be run within a browser?
(otherwise i might be in the wrong place)

**Comment by uriva** [comment]
here is the code if it helps: https://github.com/uriva/portal/blob/main/client/src/index.ts

**Comment by lucacasonato** [comment]
No, that is not the goal. This is a plug-in to enable esbuild to understand Deno style http specifiers and import maps.
