### ISSUE TITLE
npm deps, with dependencies on node libraries are not handled properly

### ISSUE THREAD

**Issue by Lunarequest** [lucacasonato/esbuild_deno_loader#93]
I use EasyMde which depends on `typo-js`. when run locally `typo-js` normally falls back to node apis and runs `var fs = require("fs");` this trips up esbuild_deno_loader which complains it should be namespaced and fails. namespacing this validly complains that i should target nodejs and not web, I know that this won't be executed and normally is treeshaken out but the plugin doesn't seem to be context aware. Would it be possible to force the loader to ignore unresolvable deps?

**Comment by lucacasonato** [comment]
Fixed by #105
