### ISSUE TITLE
importmap support local path

### ISSUE THREAD

**Issue by Decodetalkers** [lucacasonato/esbuild_deno_loader#94]
seems this plugin does not support importmap like

```json
{
"import" : {
  "~": "./src"
}
}
```

but the import_map of deno support it

**Comment by johnstonmatt** [comment]
@lucacasonato I've added a reproduction here because I noticed the same issue:
[https://github.com/polyseam/esbuild-deno-loader-bug](https://github.com/polyseam/esbuild-deno-loader-bug)

Thanks for all your hard work!

**Comment by BlackAsLight** [comment]
I've found specifying the deno.json file fixes that problem. `denoPlugins({ configPath: await Deno.realPath('./deno.json') })`

**Comment by lucacasonato** [comment]
See also #86
